# -*- coding: utf-8 -*-
"""hybrid_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F2NObyzJ6XHS-aie-HV49LuyftAfqleI
"""

!pip install ruptures

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import ruptures as rpt
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, GRU, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.optimizers import Adam
from xgboost import XGBRegressor
# Load dataset
#upload file
from google.colab import files
import io
file_ = files.upload()

df = pd.read_excel(io.BytesIO(list(file_.values())[0]))
# Inspect
print(df.head())
print(df.info())
# Assume timestamp + target column
df.columns = [col.lower() for col in df.columns]
# Rename if needed
# df.rename(columns={'timestamp_col':'timestamp', 'target_col':'value'}, inplace=True)
df['date'] = pd.to_datetime(df['date'])
df = df.sort_values('date')
df.set_index('date', inplace=True)
print("Data loaded successfully:", df.shape)
#creating target variable
df['total_energy'] = df[['mels_s', 'lig_s', 'mels_n', 'hvac_n', 'hvac_s']].sum(axis=1)
#round upto 2 decimals
cols_to_round = ['mels_s','lig_s','mels_n','hvac_n','hvac_s','total_energy']
df[cols_to_round] = df[cols_to_round].round(2)
print(df.head())
# Handle missing values
df = df.ffill()
# Remove outliers (optional)
def remove_outliers(series):
    q1, q3 = np.percentile(series, [25, 75])
    iqr = q3 - q1
    lower = q1 - 1.5 * iqr
    upper = q3 + 1.5 * iqr
    return np.clip(series, lower, upper)
df['total_energy'] = remove_outliers(df['total_energy'])
# Normalize later after features
print("Preprocessing done")
def create_features(df):
    df_feat = df.copy()
    # Time features
    df_feat['hour'] = df_feat.index.hour
    df_feat['dayofweek'] = df_feat.index.dayofweek
    # Cyclic encoding
    df_feat['hour_sin'] = np.sin(2 * np.pi * df_feat['hour']/24)
    df_feat['hour_cos'] = np.cos(2 * np.pi * df_feat['hour']/24)
    df_feat['dow_sin'] = np.sin(2 * np.pi * df_feat['dayofweek']/7)
    df_feat['dow_cos'] = np.cos(2 * np.pi * df_feat['dayofweek']/7)
    # Lag features
    df_feat['lag_1'] = df_feat['total_energy'].shift(1)
    df_feat['lag_24'] = df_feat['total_energy'].shift(24)
    df_feat['lag_168'] = df_feat['total_energy'].shift(168)
    # Rolling stats
    df_feat['roll_mean_24'] = df_feat['total_energy'].rolling(24).mean()
    df_feat['roll_std_24'] = df_feat['total_energy'].rolling(24).std()
    df_feat = df_feat.dropna()
    return df_feat
df_feat = create_features(df)
print("Features created:", df_feat.shape)
#splitting of data
split_idx = int(len(df) * 0.8)
train_df = df.iloc[:split_idx]
test_df = df.iloc[split_idx:]






Chnage_points = [6452,
7128,
13854,
13957,
15192,
15599]

split_idx = int(len(df_feat) * 0.8)

train_df = df_feat.iloc[:split_idx]
test_df  = df_feat.iloc[split_idx:]

feature_cols = [col for col in df_feat.columns if col != 'total_energy']

scaler_X = StandardScaler()
scaler_y = MinMaxScaler()

X_train = scaler_X.fit_transform(train_df[feature_cols])
X_test  = scaler_X.transform(test_df[feature_cols])

y_train = scaler_y.fit_transform(train_df[['total_energy']])
y_test  = scaler_y.transform(test_df[['total_energy']])

def create_sequences(X, y, seq_len=24):
    Xs, ys = [], []
    for i in range(seq_len, len(X)):
        Xs.append(X[i-seq_len:i])
        ys.append(y[i])
    return np.array(Xs), np.array(ys)

seq_len = 24

X_train_seq, y_train_seq = create_sequences(X_train, y_train, seq_len)
X_test_seq, y_test_seq   = create_sequences(X_test, y_test, seq_len)

model = Sequential([
    GRU(64, return_sequences=True, input_shape=(seq_len, X_train_seq.shape[2])),
    Dropout(0.2),
    GRU(32),
    Dense(1)
])

model.compile(optimizer=Adam(0.001), loss='mse')

callbacks = [
    EarlyStopping(patience=5, restore_best_weights=True),
    ReduceLROnPlateau(patience=3)
]

model.fit(
    X_train_seq, y_train_seq,
    epochs=30,
    batch_size=64,
    validation_split=0.2,
    callbacks=callbacks,
    verbose=1
)

y_train_pred_gru = model.predict(X_train_seq)
y_test_pred_gru  = model.predict(X_test_seq)

y_train_residual = y_train_seq - y_train_pred_gru

change_points = [6452, 7128, 13854, 13957, 15192, 15599]

# Filter change points that fall within the training data range (relative to df_feat)
# train_df corresponds to df_feat.iloc[:split_idx]
# X_train is scaled train_df features, so its length is len(train_df)
relevant_cps_train = [cp for cp in change_points if cp < len(train_df)]

# Take the last relevant change point for the local model start
# If no change points are relevant, default to a sensible start (e.g., 0 or a fixed length from the end)
if relevant_cps_train:
    local_start = relevant_cps_train[-1]
else:
    # Fallback if no change points are within the training data range
    # For example, use a fixed percentage or number of recent points
    # For now, let's assume there will always be at least one relevant change point.
    # If not, this logic needs to be more robust. Let's use the last 20% of X_train if no CPs.
    local_start = int(len(X_train) * 0.8)

X_local = X_train[local_start:]
y_local_res = y_train_residual[-len(X_local):]

xgb_model = XGBRegressor(
    n_estimators=300,
    max_depth=5,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8
)

xgb_model.fit(X_local, y_local_res)

residual_pred = xgb_model.predict(X_test[seq_len:])

# simple drift proxy: distance from train mean
train_mean = np.mean(X_train, axis=0)
test_dist = np.linalg.norm(X_test - train_mean, axis=1)

# normalize
w = (test_dist - test_dist.min()) / (test_dist.max() - test_dist.min())
w = w[seq_len:]

y_final = (
    (1 - w.reshape(-1,1)) * y_test_pred_gru +
    w.reshape(-1,1) * (y_test_pred_gru + residual_pred.reshape(-1,1))
)

y_test_actual = scaler_y.inverse_transform(y_test_seq)
y_final_inv   = scaler_y.inverse_transform(y_final)

print("R2:", r2_score(y_test_actual, y_final_inv))
print("MAE:", mean_absolute_error(y_test_actual, y_final_inv))

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

print("RMSE: ", np.sqrt(mean_squared_error(y_test_actual, y_final_inv)))
print("MAE: ", mean_absolute_error(y_test_actual, y_final_inv))



